# System Config
server:
  servlet:
    context-path: /tam
  port: 8088

# DataSource Config
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/tam?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20111124

# Activiti Config
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: audit

# Logger Config
logging:
  level:
    com.rango.tam: debug

# MybatisPlus Config
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Netty Config
netty:
  tcp:
    server:
      host: 127.0.0.1
      port: 8024
