server:
  servlet:
    context-path: /tam
  port: 8088
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tam?serverTimezone=Asia/Shanghai
    username: root
    password: 20111124
